#!/bin/bash

if [[ $_ == $0 ]]; then
    echo "Sorry but this script needs to be sourced and not executed"
    exit 1
fi

TARGET_ARCH=$(get_build_var TARGET_ARCH)

if [ -z "$TARGET_ARCH" ]; then
    echo "No TARGET_ARCH found, cannot continue"
    return 1;
fi

try_copy_out_file() {
    src=${ANDROID_PRODUCT_OUT}/$1
    trg=../bin/${TARGET_ARCH}/
    
    if [ -f $src ]; then
        echo "Copying $1 to $target"
        mkdir -p $trg
        cp -v ${src} ${trg}
    else
        echo "No $1 found."
    fi
}

if [ -d $ANDROID_PRODUCT_OUT ]; then
    try_copy_out_file vendor/bin/grabservice
    try_copy_out_file vendor/bin/grabservice-hw
    try_copy_out_file vendor/bin/grabservice-vnd
else
    echo "Nothing in $ANDROID_PRODUCT_OUT. Did you build the AOSP?"
fi

